const  info = [
  // "australia",
  "accessControl",
  // "australia.southAustralia",
  // "australia.southAustralia.adelaide",
  // "australia.southAustralia.mountGambier",
  // "australia.victoria",
  // "australia.victoria.labor",
  // "australia.victoria.liberal",
  // "canada",
  // "canada.alberta",
  // "canada.alberta.fauna",
  // "canada.alberta.flora",
  // "canada.quebecCity",
  // "canada.quebecCity.airdrie",
  // "canada.quebecCity.spruceGrove",
  // "england",
  // "england.cuisine",
  // "england.cuisine.luton",
  // "england.cuisine.visualArts",
  // "england.folklore",
  // "england.folklore.berkshire",
  // "england.folklore.bristol",
  // "india",
  // "india.madhyaPradesh",
  // "india.madhyaPradesh.bhopal",
  // "india.madhyaPradesh.indore",
  // "india.rajasthan",
  // "india.rajasthan.jaipur",
  // "india.rajasthan.udaipur",
];

module.exports = info;